### ISSUE TITLE
When I try to use non-continuous learning to obtain “Upper-Bound” data

### ISSUE THREAD

**Issue by ArkNightmaster** [sun-hailong/LAMDA-PILOT#15]
"prefix": "reproduce",
    "dataset": "imagenetr",
    "memory_size": 0,
    "memory_per_class": 0,
    "fixed_memory": false,
    "shuffle": true,
    "init_cls": 200,
    "increment": 0,
    "model_name": "finetune",
    "backbone_type": "vit_base_patch16_224",
    "device": ["1"],
    "seed": [1993],
    "init_epoch": 20,
    "init_lr": 1e-3,
    "init_milestones": [60, 120, 170],
    "init_lr_decay": 0.1,
    "init_weight_decay": 0.0005,
    "epochs": 20,
    "lrate": 1e-3,
    "milestones": [40, 70],
    "lrate_decay": 0.1,
    "batch_size": 128,
    "weight_decay": 2e-4

**As you can see, when I set init_cls=200 and incremental=0 (which aligns with our intuition in non continuous learning scenarios).
But a bug occurred:**

Traceback (most recent call last):
File "/media/user/data1/ldz cil/clip4prompt/main. py", line 33, in<module>
Main()
File "/media/user/data1/ldz cil/clip4prompt/main. py", line 19, in main
Train (args)
File "/media/user/data1/ldz cil/clip4prompt/trainer. py", line 19, in train
_Train (args)
File "/media/user/data1/ldz cil/clip4prompt/trainer. py", line 77, in train
Cnn.accy, nme-accy=model. eval_task()
File "/media/user/data1/ldz cil/clip4prompt/models/base. py", line 118, in eval_task
Cnn.accy=self_ Evaluate (y_pred, y_true)
File "/media/user/data1/ldz cil/clip4prompt/models/base. py", line 106, in _evaluate
Grouped=accuracy (y_pred. T [0], y_true, self. _knowledge-based classes, self. args ["init_cls"], self. args ["increment"])
File "/media/user/data1/ldz cil/clip4prompt/utils/toolkit. py", line 121, in accuracy
For class_id in range (init_cls, np. max (y_true), increase):
Value Error: range() arg 3 must not be zero

**Is this setting correct? Or rather, the author did not provide an interface to retrieve Upper data**

**Comment by ArkNightmaster** [comment]
> Hi @ArkNightmaster , Thanks for your interest in our repository. I think you can change the printing process and subsequently fix the issue. The problem lies in the 'increase' set to 0, which is being printed in the log. You can rectify this by following the information provided in the log.

Hi @sun-hailong ,
Thanks for your timely response, but it seems that I did not get the answer I wanted. I would like to know if there is a method in the PILOT repository that can calculate the Upper Bound. If not, will we consider adding it in the future?
